# Generated by Django 4.2.11 on 2024-05-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="about_image2",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
