# Generated by Django 4.2.11 on 2024-05-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_news_about_image2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
