# Generated by Django 4.2.11 on 2024-05-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_regions_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_user",
            field=models.ImageField(
                default="/media/avatar_user.png", upload_to="profile_images/"
            ),
        ),
    ]
