# Generated by Django 4.2.11 on 2024-05-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_profile_avatar_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar_user",
            field=models.ImageField(
                default="/avatar_user.png", upload_to="profile_images/"
            ),
        ),
    ]
