# Generated by Django 4.2.11 on 2024-05-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_profile_avatar_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="title_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chat",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
